use core::{
    marker::PhantomData,
    sync::atomic::{Ordering, fence},
};

use cortex_m::peripheral::DWT;
use stm32f4xx_hal::{
    gpio::{PinState, Speed},
    time::Hertz,
};

use dxkb_common::{
    dev_trace, util::{self, bit_array_size, BitArray, BitMatrix, BitMatrixLayout, ColBitMatrixLayout}, KeyState
};

use crate::pin_set::{PinSet, PinSetSized};

// /**
//  * Represents a type that is able to read one or multiple times from a set of input pins, returning the result of folding all the results of every read sample.
//  */
// pub trait AggregateRead {
//     type ReadResult<const PINS: u8, Src: InputPins<PINS>>: InputRead;

//     fn read_all<const PINS: u8, T: InputPins<PINS>>(pins: &T) -> Self::ReadResult<PINS, T>;
// }

// /**
//  * Indicates that each pin must be read exactly once for each matrix scan.
//  */
// pub struct SingleShotRead;

// impl AggregateRead for SingleShotRead {
//     type ReadResult<const PINS: u8, Src: InputPins<PINS>> = Src::ReadResult;

//     fn read_all<const PINS: u8, T: InputPins<PINS>>(pins: &T) -> Self::ReadResult<PINS, T> {
//         pins.read_inputs()
//     }
// }

// /**
//  * Indicates that each pin will be read [`OVER`] number of times for each matrix
//  * scan, leaving a delay between each sample read.
//  */
// pub struct OversamplingRead<
//     const OVER: usize = 16,
//     const DELAY_CYCLES: u32 = 2>
// ;

// impl <
//     const OVER: usize,
//     const DELAY_CYCLES: u32
// > AggregateRead for OversamplingRead<OVER, DELAY_CYCLES> {
//     type ReadResult<const PINS: u8, Src: InputPins<PINS>> = OversamplingReadResults<OVER, Src::ReadResult>;

//     fn read_all<const PINS: u8, T: InputPins<PINS>>(pins: &T) -> Self::ReadResult<PINS, T> {
//         let results = util::slice::array_initialize(|_| {
//             cortex_m::asm::delay(DELAY_CYCLES);
//             pins.read_inputs()
//         });

//         OversamplingReadResults {
//             read_result: results
//         }
//     }
// }

/// Represents a type that is able to debounce the input signal
/// generated by a button, attempting to remove the noise generated by
/// the effect of pressing or unpressing it.
pub trait Debounce<const ROWS: u8, const COLS: u8> {
    fn debounce(
        &mut self,
        row: u8,
        col: u8,
        current_millis: u32,
        prev_state: KeyState,
        last_read_state: KeyState,
    ) -> KeyState;
}

/// A debounce strategy where no debounce is done. Button status is
/// passed to the matrix as it is coming from the wire.
pub struct NoDebouncer {}
impl<const ROWS: u8, const COLS: u8> Debounce<ROWS, COLS> for NoDebouncer {
    fn debounce(
        &mut self,
        _row: u8,
        _col: u8,
        _current_millis: u32,
        _prev_state: KeyState,
        last_read_state: KeyState,
    ) -> KeyState {
        last_read_state
    }
}

// Following a similar naming than QMK
/// Debounce strategy in which a level change in the wire immediately
/// triggers a change in the button state (pressed or unpressed,
/// depending on the new level), and any other change in the wire for
/// that specific button is ignored for the following
/// `DEBOUNCE_MILLIS` milliseconds. For reducing the memory
/// footprint, the maximum debounce time is limited to 254 ms.
pub struct DebouncerEagerPerKey<const ROWS: u8, const COLS: u8, const DEBOUNCE_MILLIS: u8>
where
    [(); (ROWS as usize) * (COLS as usize)]:,
{
    // Holds the last time, in millis, when each key was pressed,
    // except if its value is 0xff. In such case, it is considered
    // that the last event for the referred key happened a long time
    // ago, and next event coming from this key can be applied. This
    // is a trick that QMK uses for handling the fact that a u8 value
    // that represents millis will constantly be wrapping, and
    // therefore, zero is a perfectly valid value. Therefore, instead
    // of zero, we reserve the value 0xff as a special value for
    // represent this case.
    last_change_millis: [u8; (ROWS as usize) * (COLS as usize)],
}

impl<const ROWS: u8, const COLS: u8, const DEBOUNCE_MILLIS: u8>
    DebouncerEagerPerKey<ROWS, COLS, DEBOUNCE_MILLIS>
where
    [(); (ROWS as usize) * (COLS as usize)]:,
{
    const fn assert_debounce_millis_in_range(millis: u8) {
        assert!(millis < 255, "Debounce time cannot be greater than 254 ms!");
    }

    pub fn new() -> Self {
        const { Self::assert_debounce_millis_in_range(DEBOUNCE_MILLIS) };

        DebouncerEagerPerKey {
            last_change_millis: [0xffu8; (ROWS as usize) * (COLS as usize)],
        }
    }

    pub const fn diff_time(newer: u8, older: u8) -> u8 {
        if newer >= older {
            newer - older
        } else {
            255 - older + newer
        }
    }
}

impl<const ROWS: u8, const COLS: u8, const DEBOUNCE_MILLIS: u8> Debounce<ROWS, COLS>
    for DebouncerEagerPerKey<ROWS, COLS, DEBOUNCE_MILLIS>
where
    [(); (ROWS as usize) * (COLS as usize)]:,
{
    fn debounce(
        &mut self,
        row: u8,
        col: u8,
        current_millis: u32,
        prev_state: KeyState,
        last_read_state: KeyState,
    ) -> KeyState {
        let wrapped_millis = (current_millis % 254) as u8;
        let last_change_ms =
            &mut self.last_change_millis[row as usize * COLS as usize + col as usize];
        if *last_change_ms != 0xff {
            if Self::diff_time(wrapped_millis, *last_change_ms) < DEBOUNCE_MILLIS {
                // The last update was recent. Just ignore everything.
                return prev_state;
            } else {
                // The debounce time have already passed. Mark it as such, and continue.
                dev_trace!(
                    "Debounce time over for {}; {} ({} ms). Because {} - {} = {}",
                    row,
                    col,
                    current_millis,
                    wrapped_millis,
                    *last_change_ms,
                    Self::diff_time(wrapped_millis, *last_change_ms)
                );
                *last_change_ms = 0xff;
            }
        }

        if prev_state != last_read_state {
            // If there has been any change, report the change, and
            // store the time when it happened.
            dev_trace!(
                "Debounce time set in {} ms after {:?}",
                current_millis,
                last_read_state
            );
            *last_change_ms = wrapped_millis;
        }
        return last_read_state;
    }
}

/// Represents a type that determines the way in which a key matrix is
/// scanned. It allows to dynamically determine which will be the type
/// of the input pins and the output pins depending on the direction
/// in which the matrix should be scanned according to the type that
/// conforms to this trait. See [`ColumnScan`] and [`RowScan`] for
/// more info.
pub trait MatrixScan<const ROWS: u8, const COLS: u8, RowPins, ColPins> {
    type InPins: PinSet;
    type OutPins: PinSet;

    fn translate_pins(rows: RowPins, cols: ColPins) -> (Self::InPins, Self::OutPins);
    fn translate_indexes(input_pin_index: u8, output_pin_index: u8) -> (u8, u8);
}

/// A type of matrix scan in which the column pins are individually
/// selected, and the row pins are read at once. This should be the
/// selected matrix scan type if your board setup has diodes connected
/// from the rows to the columns.
pub struct ColumnScan {}

impl<const ROWS: u8, const COLS: u8, RowPins, ColPins> MatrixScan<ROWS, COLS, RowPins, ColPins>
    for ColumnScan
where
    RowPins: PinSet,
    ColPins: PinSet,
{
    type InPins = RowPins;
    type OutPins = ColPins;

    fn translate_pins(rows: RowPins, cols: ColPins) -> (Self::InPins, Self::OutPins) {
        (rows, cols)
    }

    fn translate_indexes(input_pin_index: u8, output_pin_index: u8) -> (u8, u8) {
        (input_pin_index, output_pin_index)
    }
}

/// A type of matrix scan in which the row pins are individually
/// selected, and the column pins are read at once. This should be the
/// selected matrix scan type if your board setup has diodes connected
/// from the columns to the rows.
pub struct RowScan {}

impl<const ROWS: u8, const COLS: u8, RowPins, ColPins> MatrixScan<ROWS, COLS, RowPins, ColPins>
    for RowScan
where
    RowPins: PinSet,
    ColPins: PinSet
{
    type InPins = ColPins;
    type OutPins = RowPins;

    fn translate_pins(rows: RowPins, cols: ColPins) -> (Self::InPins, Self::OutPins) {
        (cols, rows)
    }

    fn translate_indexes(input_pin_index: u8, output_pin_index: u8) -> (u8, u8) {
        (output_pin_index, input_pin_index)
    }
}

pub trait KeyMatrixLike<const ROWS: u8, const COLS: u8> {
    fn get_key_state(&self, row: u8, col: u8) -> KeyState;
    fn set_key_state(&mut self, row: u8, col: u8, state: KeyState);

    /// Scans the current status of the key matrix, returning true if
    /// something has changed from the past scan.
    fn scan_matrix(&mut self) -> bool {
        self.scan_matrix_act(|_, _, _| {})
    }

    /// Scans the current status of the key matrix, returning true if
    /// something has changed from the past scan. The function
    /// `changed_fn` will be executed for each change detected in the
    /// matrix.
    fn scan_matrix_act<F: FnMut(u8, u8, KeyState) -> ()>(&mut self, changed_fn: F) -> bool;
}

/// A key matrix, constructed from the pins that forms the rows and
/// the columns of the matrix. In this matrix, a key is considered
/// pressed when it is active low.  More information about how key
/// matrices work:
/// <https://pcbheaven.com/wikipages/How_Key_Matrices_Works/>.
/// <br />
/// <br />
/// The definition of the key matrix is completed with the following
/// generics:
///  - `ROWS`: The number of rows in the matrix.
///  - `COLS`: The number of columns in the matrix.
///  - `RowPins`: The type that represents the row pins of the matrix.
///     They're generally represented as a tuple of pins.
///     Pin direction (input or output) depends on the matrix scan type S.
///  - `ColPins`: The type that represents the column pins of the matrix.
///    They're generally represented as a tuple of pins.
///    Pin direction (input or output) depends on the matrix scan type S.
///  - `S`: The type that indicates how the matrix will be scanned.
///    It should be set to either one of the following types:
///    - [`ColumnScan`]: The columns of the matrix are selected one by one,
///      and the rows are read all at once. In this mode, RowPins needs to
///      hold input pins, and ColPins needs to hold output pins.
///    - [`RowScan`]: The rows of the matrix are selected one by one,
///      and the columns are read all at once. In this mode, RowPins needs to
///      hold output pins, and ColPins needs to hold input pins.

pub struct KeyMatrix<const ROWS: u8, const COLS: u8, RowPins, ColPins, S, D, R>
where
    [(); ROWS as usize]:,
    S: MatrixScan<ROWS, COLS, RowPins, ColPins>,
//    R: AggregateRead,
    ColBitMatrixLayout<COLS>: BitMatrixLayout,
{
    matrix: BitMatrix<{ ROWS as usize }, COLS>,
    input_pins: S::InPins,
    output_pins: S::OutPins,
    debouncer: D,
    sysclk_freq: Hertz, // TODO Change by usage of Clock trait
}

const fn assert_pin_sets_match_matrix_dimensions(expected_rows: u8, got_rows: usize, expected_cols: u8, got_cols: usize) {
    assert!(expected_rows as usize == got_rows, "Provided row pins don't match the expected number of rows in the matrix!");
    assert!(expected_cols as usize == got_cols, "Provided column pins don't match the expected number of columns in the matrix!");
}

impl<const ROWS: u8, const COLS: u8, RowPins, ColPins, S, D, R>
    KeyMatrix<ROWS, COLS, RowPins, ColPins, S, D, R>
where
    [(); ROWS as usize]:,
    RowPins: PinSet,
    ColPins: PinSet,
    S: MatrixScan<ROWS, COLS, RowPins, ColPins>,
    D: Debounce<ROWS, COLS>,
//    R: AggregateRead,
    ColBitMatrixLayout<COLS>: BitMatrixLayout,

{
    pub fn new(sysclk_freq: Hertz, rows: RowPins, cols: ColPins, debouncer: D) -> Self {
        const {
            // Doing a const assertion rather than a type assertion because
            // otherwise the error generated by the compiler is quite confusing.
            assert_pin_sets_match_matrix_dimensions(ROWS, RowPins::NUM_PINS, COLS, ColPins::NUM_PINS)
        }

        let (mut in_pins, mut out_pins) = S::translate_pins(rows, cols);
        in_pins.make_input_pull_up();
        out_pins.make_output_push_pull();

        // No hurries :)
        in_pins.set_speed(Speed::Low);
        out_pins.set_speed(Speed::Low);

        // Using active-low for determining whether matrix buttons are pressed,
        // so all the out pins are set to 1 until they're scanned, when
        // individually become 0
        out_pins.write_all(true);

        Self {
            matrix: BitMatrix::new(),
            input_pins: in_pins,
            output_pins: out_pins,
            debouncer,
            sysclk_freq,
        }
    }
}

impl<const ROWS: u8, const COLS: u8, RowPins, ColPins, S, D, R> KeyMatrixLike<ROWS, COLS>
    for KeyMatrix<ROWS, COLS, RowPins, ColPins, S, D, R>
where
    [(); ROWS as usize]:,
    S: MatrixScan<ROWS, COLS, RowPins, ColPins>,
    D: Debounce<ROWS, COLS>,
//    R: AggregateRead,
    ColBitMatrixLayout<COLS>: BitMatrixLayout,
    [(); S::InPins::NUM_PINS]:

{
    #[inline(always)]
    fn get_key_state(&self, row: u8, col: u8) -> KeyState {
        KeyState::from_bool(self.matrix.get_value(row as usize, col))
    }

    #[inline(always)]
    fn set_key_state(&mut self, row: u8, col: u8, state: KeyState) {
        self.matrix
            .set_value(row as usize, col, state == KeyState::Pressed);
    }

    #[inline(never)]
    fn scan_matrix_act<F: FnMut(u8, u8, KeyState) -> ()>(&mut self, mut changed_fn: F) -> bool {
        let current_millis =
            ((DWT::cycle_count() as u64) * 1000 / self.sysclk_freq.raw() as u64) as u32;
        let mut has_changed = false;

        for output_pin_index in 0..S::OutPins::NUM_PINS {
            self.output_pins.write_single(output_pin_index as u32, false);
            fence(Ordering::SeqCst);

            // Checked empirically that at 96 MHz with OSPEEDR set to low, it
            // takes around 40 ns to go from High to Low.
            unsafe {
                core::arch::asm! {
                    "nop",
                    "nop",
                    "nop",
                    "nop",
                    "nop",
                };
            }

            // TODO Recover oversampling
//            let inputs = R::(&self.input_pins);
            let inputs = self.input_pins.read().get_all(); // TODO Maybe we don't need to call get_all and just is_on on every read pin
            fence(Ordering::SeqCst);

            self.output_pins.write_single(output_pin_index as u32, true);


            // Temporarily set the output pins to output and write a high in
            // them, so they can quickly charge the capacitance of the diodes in
            // the matrix, and preventing a slow loading curve that would make
            // the input pins to restore the Vdd voltage due to the high
            // impedance of the line.
            fence(Ordering::SeqCst);
            self.input_pins.make_output_push_pull();
            self.input_pins.write_all(true);
            self.input_pins.make_input_pull_up();
            fence(Ordering::SeqCst);

            // This section should be already enough to give some time to the column pin to go low.
            for input_pin_index in 0..S::InPins::NUM_PINS {
                let new_state = KeyState::from_bool(!inputs[input_pin_index]);

                let (row, col) = S::translate_indexes(input_pin_index as u8, output_pin_index as u8);
                let prev_state = self.get_key_state(row, col);

                let effective_state =
                    self.debouncer
                        .debounce(row, col, current_millis, prev_state, new_state);
                if effective_state != prev_state {
                    has_changed = true;
                    self.set_key_state(row, col, effective_state);
                    changed_fn(row, col, effective_state);
                    dev_trace!(
                        "{:?} ({}; {}) ({} ms)",
                        effective_state,
                        row,
                        col,
                        current_millis
                    );
                }
            }
        }

        has_changed
    }
}
